import type { Metadata } from "next"
import type { FC, ReactNode } from "react"
import "./globals.css"

export const metadata: Metadata = {
	title: "Create Next App",
	description: "Generated by create next app",
}

export interface RootLayoutProps {
	children: ReactNode
}

const RootLayout: FC<RootLayoutProps> = ({ children }) => {
	return (
		<html lang="ja">
			<body>{children}</body>
		</html>
	)
}

export default RootLayout
